# Generated by Django 4.1.5 on 2023-03-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='CompanyReview',
        ),
    ]
