# Generated by Django 4.1.5 on 2023-04-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_companycontact_alter_companyreview_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companycontact',
            old_name='emails',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='companycontact',
            old_name='firstname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='companycontact',
            old_name='lastname',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='companycontact',
            old_name='messages',
            new_name='message',
        ),
    ]
