# Generated by Django 4.1.5 on 2023-04-03 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_emails_companycontact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
